### ISSUE TITLE
Upload image to Docker hub

### ISSUE THREAD

**Issue by Nosskirneh** [kabiroberai/theos-docker#1]
Hi! It would be great if this image could be uploaded to Docker's hub, so that it's easy to pull it from scripts and whatnot.

https://medium.com/innovation-res/how-to-build-run-and-upload-your-docker-image-on-docker-hub-6049a2601d19

Thanks!

**Comment by Nosskirneh** [comment]
Pushed it to https://hub.docker.com/layers/nosskirneh/theos-docker/1.0/images/sha256-4dadd97989e4d8c4c6f1aff681da9b5bab976e3016a40f588d73cc81aba67bf6?context=explore

**Comment by kabiroberai** [comment]
cool! fyi the reason I hadn't uploaded this as a standalone image is that Docker Compose offers some additional affordances such as named volumes, but that's ultimately a design decision and embedding those into the image is an equally viable approach.

**Comment by Nosskirneh** [comment]
I suspected that was the case. I tried to build this the traditional way and realized there were directories missing, otherwise provided by docker-compose. Anyhow, I had planned to use this in a GitHub Actions, so I need it to be in one image without any mounted things. Will hopefully get the time to push my changes to my fork later in case anyone else is interested.
